# Use and official node.js runtime as a parent image
FROM node:22-alpine

# Set the working dirctory in the container
WORKDIR /app

# Copy the package.json and the package-lock.json files to the container
COPY package*.json .

# Install the dependancies 
RUN npm install 

# Copy the rest of the appplication code
COPY . .

# Expose the port that the app runs on
EXPOSE 5000

# Define the command to tun your application
CMD ["node", "./src/server.js"]