FROM node:22-alpine

WORKDIR /app

# Copy schema and Prisma-related files FIRST
COPY prisma ./prisma

# Copy package files and install dependencies (runs prisma generate in postinstall)
COPY package*.json ./
RUN npm install

# Then copy the rest of your app
COPY . .

EXPOSE 5000

CMD ["npm", "run", "dev"]